// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/generate-basecamp-members.js";
import * as $1 from "./routes/basecamp-members.jsx";
import * as $2 from "./routes/login.jsx";
import * as $3 from "./routes/logout.jsx";
import * as $$0 from "./islands/GenerateBasecampMembersListButton.jsx";
import * as $$1 from "./islands/LoginPage.jsx";

const manifest = {
  routes: {
    "./routes/api/generate-basecamp-members.js": $0,
    "./routes/basecamp-members.jsx": $1,
    "./routes/login.jsx": $2,
    "./routes/logout.jsx": $3,
  },
  islands: {
    "./islands/GenerateBasecampMembersListButton.jsx": $$0,
    "./islands/LoginPage.jsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
